package graphics;

import java.awt.Color;
import java.awt.geom.Line2D;
import java.awt.geom.Path2D;
import java.awt.geom.PathIterator;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a collection of colored paths generated by turtle graphics interpretation.
 * <p>
 * This class manages a sequence of path segments, each potentially with different colors,
 * created through turtle graphics commands. It maintains both a current working path and
 * a history of completed paths, allowing for complex multi-colored drawings.
 * </p>
 * <p>
 * The class supports operations typical in turtle graphics such as drawing lines and
 * appending path segments, with the ability to change colors between segments. Each
 * completed path segment is stored as a {@link ColoredPath} that pairs a geometric
 * path with its rendering color.
 * </p>
 *
 * @author Hytalo Bassi
 * @version 1.0
 * @since 1.0
 * @see ColoredPath
 */
public class TurtlePath {
    /** The default color for new path segments. */
    private final Color color;
    
    /** The current path segment being constructed. */
    private ColoredPath currentPath;

    /** The collection of completed colored path segments. */
    private List<ColoredPath> coloredPaths;

    /**
     * Constructs a new TurtlePath with the specified default color.
     * <p>
     * Initializes an empty path with the given color applied to all segments
     * unless explicitly overridden.
     * </p>
     *
     * @param defaultColor the default color for path segments
     */
    public TurtlePath(Color defaultColor) {
        currentPath = new ColoredPath();
        color = defaultColor;
        currentPath.setColor(defaultColor);

        coloredPaths = new ArrayList<>();
    }

    /**
     * Constructs a new TurtlePath with black as the default color.
     * <p>
     * Initializes an empty path with black color applied to all segments
     * unless explicitly overridden.
     * </p>
     */
    public TurtlePath() {
        color = Color.BLACK;
        currentPath = new ColoredPath();
        currentPath.setColor(color);
        coloredPaths = new ArrayList<>();
    }

    /**
     * Adds a line segment to the path from the specified starting point to the ending point.
     * <p>
     * This method creates a new path segment, moves to the starting coordinates,
     * draws a line to the ending coordinates, and finalizes the segment.
     * </p>
     *
     * @param x1 the x-coordinate of the starting point
     * @param y1 the y-coordinate of the starting point
     * @param x2 the x-coordinate of the ending point
     * @param y2 the y-coordinate of the ending point
     */
    public void addLine(double x1, double y1, double x2, double y2) {
        currentPath.moveTo(x1, y1);
        currentPath.lineTo(x2, y2);
        finishPath();
    }

    /**
     * Adds a line segment to the path using a Line2D object.
     * <p>
     * This is a convenience method that extracts coordinates from the Line2D
     * object and delegates to {@link #addLine(double, double, double, double)}.
     * </p>
     *
     * @param line the Line2D object containing the line segment coordinates
     */
    public void addLine(Line2D.Double line) {
        addLine(line.x1, line.y1, line.x2, line.y2);
    }

    /**
     * Returns a list of all geometric paths without color information.
     * <p>
     * This method extracts only the Path2D components from each ColoredPath,
     * discarding color information. Useful for operations that only require
     * geometric data.
     * </p>
     *
     * @return an unmodifiable view of all path geometries
     */
    public List<Path2D.Double> getPaths() {
        List<Path2D.Double> paths2d = new ArrayList<>();
        for (ColoredPath coloredPath : coloredPaths) {
            paths2d.add(coloredPath.getPath());
        }

        return paths2d;
    }

    /**
     * Returns a list of all colored path segments.
     * <p>
     * This method provides access to the complete collection of path segments
     * with their associated colors, enabling color-aware rendering.
     * </p>
     *
     * @return the list of all ColoredPath segments
     */
    public List<ColoredPath> getColoredPaths() {
        return coloredPaths;
    }

    /**
     * Appends another path to this TurtlePath using the default color.
     * <p>
     * This method finalizes the current path, appends the new path iterator,
     * and then finalizes the appended segment.
     * </p>
     *
     * @param newPath the path iterator to be appended
     * @param connect if {@code true}, creates connecting lines between the current
     *                path and the new path; if {@code false}, starts a new subpath
     */
    public void append(PathIterator newPath, boolean connect) {
        finishPath();
        currentPath.append(newPath, connect);
        finishPath();
    }

    /**
     * Appends another path to this TurtlePath with a specified color.
     * <p>
     * This method finalizes the current path, appends the new path iterator,
     * applies the specified color to the appended segment, and then finalizes it.
     * </p>
     *
     * @param newPath the path iterator to be appended
     * @param connect if {@code true}, creates connecting lines between the current
     *                path and the new path; if {@code false}, starts a new subpath
     * @param newColor the color to apply to the appended path segment
     */
    public void append(PathIterator newPath, boolean connect, Color newColor) {
        finishPath();
        currentPath.append(newPath, connect);
        currentPath.setColor(newColor);
        finishPath();
    }

    /**
     * Finalizes the current path segment and prepares for a new one.
     * <p>
     * This method adds the current path to the collection of completed paths
     * and creates a new empty path with the default color. This enables
     * multi-segment paths with different colors.
     * </p>
     */
    private void finishPath() {
        coloredPaths.add(currentPath);
        currentPath = new ColoredPath();
        currentPath.setColor(color);
    }

    /**
     * Represents a geometric path paired with a rendering color.
     * <p>
     * This inner class encapsulates a Path2D along with its associated color,
     * providing a complete description of a drawable path segment. It delegates
     * path construction operations to the underlying Path2D object while maintaining
     * color information.
     * </p>
     *
     * @author Hytalo
     * @version 1.0
     * @since 1.0
     */
    public static class ColoredPath {
        /** The color used to render this path. */
        private Color color;

        /** The geometric path data. */
        private Path2D.Double path;

        /**
         * Constructs a new ColoredPath with the specified color.
         *
         * @param color the color for rendering this path
         */
        public ColoredPath(Color color) {
            this.color = color;
            path = new Path2D.Double();
        }

        /**
         * Constructs a new ColoredPath with black as the default color.
         */
        public ColoredPath() {
            this.color = Color.BLACK;
            path = new Path2D.Double();
        }

        /**
         * Sets the rendering color for this path.
         *
         * @param newColor the new color to apply
         */
        public void setColor(Color newColor) {
            color = newColor;
        }

        /**
         * Returns the rendering color of this path.
         *
         * @return the current color
         */
        public Color getColor() {
            return this.color;
        }

        /**
         * Returns the geometric path data.
         *
         * @return the Path2D object containing the path geometry
         */
        public Path2D.Double getPath() {
            return path;
        }

        /**
         * Appends the geometry from a PathIterator to this path.
         * <p>
         * This method delegates to the underlying Path2D's append method,
         * allowing complex path construction from existing path iterators.
         * </p>
         *
         * @param pi the path iterator providing geometry to append
         * @param connect if {@code true}, a line segment is added to connect
         *                the current path to the new path; if {@code false},
         *                the new path begins a new subpath
         */
        public void append(PathIterator pi, boolean connect) {
            path.append(pi, connect);
        }

        /**
         * Moves the current drawing position to the specified coordinates.
         * <p>
         * This starts a new subpath at the given location without drawing.
         * </p>
         *
         * @param x the x-coordinate of the new position
         * @param y the y-coordinate of the new position
         */
        public void moveTo(double x, double y) {
            path.moveTo(x, y);
        }

        /**
         * Draws a line from the current position to the specified coordinates.
         * <p>
         * This adds a straight line segment to the path and updates the
         * current drawing position.
         * </p>
         *
         * @param x the x-coordinate of the line's end point
         * @param y the y-coordinate of the line's end point
         */
        public void lineTo(double x, double y) {
            path.lineTo(x, y);
        }
    }
}
